// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _READ_TRIM_AND_VERIFY_H_
#define _READ_TRIM_AND_VERIFY_H_

EXTERN_PATTERN( p_read_trim_and_verify )

#endif
