// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _READ_TRIM_AND_VERIFYX128_H_
#define _READ_TRIM_AND_VERIFYX128_H_

EXTERN_PATTERN( p_read_trim_and_verifyX128 )

#endif
